### ISSUE TITLE
Sample crashes on item click in recyclerview

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross-AndroidSupport#32]
Start app, click one of the items in the list. BAM!

```
07-01 10:07:56.100 I/MonoDroid( 6896): UNHANDLED EXCEPTION:
07-01 10:07:56.102 I/MonoDroid( 6896): System.NullReferenceException: Object reference not set to an instance of an object
07-01 10:07:56.102 I/MonoDroid( 6896): at Cirrious.MvvmCross.ViewModels.MvxCommand.Execute (object) <IL 0x0000f, 0x00090>
07-01 10:07:56.102 I/MonoDroid( 6896): at Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerViewHolder.ExecuteCommandOnItem (System.Windows.Input.ICommand) [0x0002f] in c:\vcs\git\MvvmCross-AndroidSupport\Cirrious.MvvmCross.Droid.Support.RecyclerView\MvxRecyclerViewHolder.cs:76
07-01 10:07:56.102 I/MonoDroid( 6896): at Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerViewHolder.<EnsureClickOverloaded>b__0 (object,System.EventArgs) [0x00000] in c:\vcs\git\MvvmCross-AndroidSupport\Cirrious.MvvmCross.Droid.Support.RecyclerView\MvxRecyclerViewHolder.cs:47
07-01 10:07:56.102 I/MonoDroid( 6896): at Android.Views.View/IOnClickListenerImplementor.OnClick (Android.Views.View) [0x0000d] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.View.cs:1923
07-01 10:07:56.102 I/MonoDroid( 6896): at Android.Views.View/IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.View.cs:1888
07-01 10:07:56.102 I/MonoDroid( 6896): at (wrapper dynamic-method) object.fabb184c-2de3-4bcd-9df3-d56f69641999 (intptr,intptr,intptr) <IL 0x00017, 0x00043>
07-01 10:07:56.110 W/art     ( 6896): JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
07-01 10:07:56.112 D/AndroidRuntime( 6896): Shutting down VM
An unhandled exception occured.

07-01 10:07:59.455 E/AndroidRuntime( 6896): FATAL EXCEPTION: main
07-01 10:07:59.455 E/AndroidRuntime( 6896): Process: com.mvvmcross.androidsupport.example, PID: 6896
07-01 10:07:59.455 E/AndroidRuntime( 6896): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
07-01 10:07:59.455 E/AndroidRuntime( 6896): Caused by: java.lang.reflect.InvocationTargetException
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at java.lang.reflect.Method.invoke(Native Method)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at java.lang.reflect.Method.invoke(Method.java:372)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     ... 1 more
07-01 10:07:59.455 E/AndroidRuntime( 6896): Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
07-01 10:07:59.455 E/AndroidRuntime( 6896): at Cirrious.MvvmCross.ViewModels.MvxCommand.Execute (object) <IL 0x0000f, 0x00090>
07-01 10:07:59.455 E/AndroidRuntime( 6896): at Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerViewHolder.ExecuteCommandOnItem (System.Windows.Input.ICommand) [0x0002f] in c:\vcs\git\MvvmCross-AndroidSupport\Cirrious.MvvmCross.Droid.Support.RecyclerView\MvxRecyclerViewHolder.cs:76
07-01 10:07:59.455 E/AndroidRuntime( 6896): at Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerViewHolder.<EnsureClickOverloaded>b__0 (object,System.EventArgs) [0x00000] in c:\vcs\git\MvvmCross-AndroidSupport\Cirrious.MvvmCross.Droid.Support.RecyclerView\MvxRecyclerViewHolder.cs:47
07-01 10:07:59.455 E/AndroidRuntime( 6896): at Android.Views.View/IOnClickListenerImplementor.OnClick (Android.Views.View) [0x0000d] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.View.cs:1923
07-01 10:07:59.455 E/AndroidRuntime( 6896): at Android.Views.View/IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.View.cs:1888
07-01 10:07:59.455 E/AndroidRuntime( 6896): at (wrapper dynamic-method) object.fabb184c-2de3-4bcd-9df3-d56f69641999 (intptr,intptr,intptr) <IL 0x00017, 0x00043>
07-01 10:07:59.455 E/AndroidRuntime( 6896): 
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:29)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at android.view.View.performClick(View.java:4781)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at android.view.View$PerformClick.run(View.java:19873)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at android.os.Handler.handleCallback(Handler.java:739)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at android.os.Handler.dispatchMessage(Handler.java:95)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at android.os.Looper.loop(Looper.java:135)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     at android.app.ActivityThread.main(ActivityThread.java:5289)
07-01 10:07:59.455 E/AndroidRuntime( 6896):     ... 4 more
07-01 10:08:45.391 I/Process ( 6896): Sending signal. PID: 6896 SIG: 9
```

**Comment by Cheesebaron** [comment]
Might be this:

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Samples/Example.Core/ViewModels/RecyclerViewModel.cs#L38
